[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.3.0"
  NPM_FLAGS = "--version"
  NPM_USE_LOCAL = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]